name: Update Version

on:
  push:
    tags:
      - 'v*'  # Ejecuta este flujo de trabajo cuando se empuje un tag que empiece con 'v'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Verificar existencia de update.json
        run: ls -la && (cat update.json || echo "update.json no encontrado")

      - name: Crear update.json si no existe
        run: |
          if [ ! -f update.json ]; then
            echo '{"version": "0.0.0", "updateUrl": "https://kiosko-42d08.web.app"}' > update.json
          fi

      - name: Update version in update.json
        run: |
          # Obtener la versión del tag (sin el prefijo 'v')
          VERSION=${GITHUB_REF#refs/tags/v}

          # Reemplazar la versión en el archivo update.json
          jq --arg version "$VERSION" '.version = $version' update.json > tmp.json && mv tmp.json update.json

      - name: Commit updated update.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git add update.json
          git commit -m "Actualizar versión a $VERSION"
          git push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/emaxD2/kiosko.git main